### ISSUE TITLE
Combination of denofunc@0.7.0 and deno@1.11.x do not work properly

### ISSUE THREAD

**Issue by horihiro** [anthonychu/azure-functions-deno-worker#38]
semver@1.3.0 (introduced by PR https://github.com/anthonychu/azure-functions-deno-worker/pull/35) causes the following error on denofunc 0.7.0 and deno v1.11.x .

Error:

```
$ denofunc
Check https://raw.githubusercontent.com/anthonychu/azure-functions-deno-worker/v0.7.0/denofunc.ts
error: TS2339 [ERROR]: Property 'operator' does not exist on type 'never'.
    if (high!.operator === comp || high!.operator === ecomp) {
              ~~~~~~~~
    at https://deno.land/x/semver@v1.3.0/mod.ts:1733:15

TS2339 [ERROR]: Property 'operator' does not exist on type 'never'.
    if (high!.operator === comp || high!.operator === ecomp) {
                                         ~~~~~~~~
    at https://deno.land/x/semver@v1.3.0/mod.ts:1733:42

TS2339 [ERROR]: Property 'operator' does not exist on type 'never'.
      (!low!.operator || low!.operator === comp) &&
             ~~~~~~~~
    at https://deno.land/x/semver@v1.3.0/mod.ts:1740:14

TS2339 [ERROR]: Property 'operator' does not exist on type 'never'.
      (!low!.operator || low!.operator === comp) &&
                              ~~~~~~~~
    at https://deno.land/x/semver@v1.3.0/mod.ts:1740:31

TS2339 [ERROR]: Property 'semver' does not exist on type 'never'.
      ltefn(version, low!.semver)
                          ~~~~~~
    at https://deno.land/x/semver@v1.3.0/mod.ts:1741:27

TS2339 [ERROR]: Property 'operator' does not exist on type 'never'.
    } else if (low!.operator === ecomp && ltfn(version, low!.semver)) {
                    ~~~~~~~~
    at https://deno.land/x/semver@v1.3.0/mod.ts:1744:21

TS2339 [ERROR]: Property 'semver' does not exist on type 'never'.
    } else if (low!.operator === ecomp && ltfn(version, low!.semver)) {
                                                             ~~~~~~
    at https://deno.land/x/semver@v1.3.0/mod.ts:1744:62
```

Environment:
```
$ deno --version
deno 1.11.5 (release, x86_64-unknown-linux-gnu)
v8 9.1.269.35
typescript 4.3.2
```
